"""0001

Revision ID: be7c98559065
Revises: 
Create Date: 2025-04-13 00:46:49.563085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7c98559065'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('odds', sa.Numeric(), nullable=False),
    sa.Column('deadline', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'TEAM_ONE_WON', 'TEAM_TWO_WON', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.execute('DROP TYPE IF EXISTS status')
    # ### end Alembic commands ###
