"""0001

Revision ID: e7133d2eb0f3
Revises: 
Create Date: 2025-04-15 13:00:03.674009

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7133d2eb0f3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("events",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("bet_amount", sa.Numeric(), nullable=False),
    sa.Column("status", sa.Enum("IN_PROGRESS", "WIN", "FAIL", name="status"), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.execute("DROP TYPE IF EXISTS status")
    # ### end Alembic commands ###
